---

# первым выкатывается контейнер с проверкой,
# при успешном результате идёт выкат на второй контейнер
#- name: Run prod container
#  docker:
#    name: app-prod
#    image: "app:{{ version }}"
#    env:
#      VIRTUAL_PORT: 8080
#      VIRTUAL_HOST: localhost

- name: Start pre prod 
  docker:
    name: app-second
    image: "app:{{ version }}"
    state: restarted
    env:
      VIRTUAL_PORT: 8080
      VIRTUAL_HOST: localhost
  tags:
    - rollback

# стоит таймер на 20 сек, чтобы в контейнере успело стартануть приложение
# прогревание проги на джаве даёт простой - тюнить таймауты в проксе
- name: Check pre prod
  shell: sleep 20s && curl http://localhost -H "Host:localhost"
  register: check_result
  failed_when: check_result.stdout != "hello world"
  tags:
    - check
    - rollback
  notify:
    - deploy on  prod
