---

- name: Run the mainbook
  hosts: 192.168.1.31
  user: docker
  sudo: yes
  roles:

# установка всего и вся на хосте
    - { role: setup, tags: setup }

# pull репы и сборка проекта и контейнера
    - { role: build, tags: build }

# выкат новых контейнеров
    - { role: deploy, tags: deploy }

# откат на версию назад
    - { role: rollback, tags: rollback }
