---

- name: Run the mainbook

# предопределить в вызове
# хост (передавать пароль на sudo и ssh - если без сертификата)
# пользователя (должны быть docker wheel группы)
#
  hosts: {{ r_host }}
  user: {{ r_user }}
  sudo: yes
  roles:

# установка всего и вся на хосте + запуск proxy
    - { role: setup, tags: setup }

# pull репы и сборка проекта, образа контейнера
    - { role: build, tags: build }

# выкат новых контейнеров или старых, с проверкой
    - { role: deploy, tags: deploy }

# роль rollback вызывать с передачей  версии (tag) образа контейнера
