---

- name: Run the mainbook
  hosts: test-onefactor-centos7
  user: roman
  sudo: yes
  roles:

# установка всего и вся на хосте + запуск proxy
    - { role: setup, tags: setup }

# pull репы и сборка проекта, контейнера
    - { role: build, tags: build }

# выкат новых контейнеров c проверкой
    - { role: deploy, tags: deploy }

# откат на версию назад
    - { role: rollback, tags: rollback }
